<?php

namespace App\Interfaces\HTTP\Controllers;

use App\Application\AI\GenerateAssessmentFromCourse;
use App\Application\AI\SendMessageToAI;
use App\Application\Services\GeminiService;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AIController extends Controller
{
    /**
     * Generate AI assessment for a course
     */
    public function generateAssessment(int $courseId, GenerateAssessmentFromCourse $action)
    {
        $result = $action->execute($courseId);
        
        if ($result['status'] === 'success') {
            return response()->json([
                'status' => 'success',
                'data' => $result['data'],
                'message' => 'AI Assessment generated successfully'
            ]);
        }

        return response()->json($result, 400);
    }

    /**
     * AI Chat / Tutor
     */
    public function chat(Request $request, SendMessageToAI $action)
    {
        $validator = Validator::make($request->all(), [
            'message' => 'required|string|max:2000',
            'course_id' => 'nullable|integer|exists:courses,id'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'message' => 'Validation error',
                'data' => $validator->errors()
            ], 422);
        }

        $result = $action->execute($request->message, $request->course_id);

        if ($result['status'] === 'success') {
            return response()->json([
                'status' => 'success',
                'data' => ['reply' => $result['content']],
                'message' => ''
            ]);
        }

        return response()->json($result, 500);
    }

    /**
     * Save AI-generated assessment to database
     */
    public function saveAssessment(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'course_id' => 'required|integer|exists:courses,id',
            'title' => 'required|string|max:255',
            'questions' => 'required|array|min:1',
            'questions.*.question' => 'nullable|string',
            'questions.*.question_text' => 'nullable|string',
            'questions.*.options' => 'required|array|min:2',
            'questions.*.correct_answer' => 'required|string',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'message' => 'Validation error',
                'data' => $validator->errors()
            ], 422);
        }

        $user = $request->user();
        $instructorId = $user->instructor ? $user->instructor->id : null;

        // Create the Assessment record
        $assessment = \App\Models\Assessment::create([
            'course_id' => $request->course_id,
            'instructor_id' => $instructorId,
            'type' => 'mcq',
            'title' => $request->title,
            'description' => 'Auto-generated by Gemini AI',
            'status' => 'active',
            'auto_generated' => true,
            'duration_minutes' => 30, // Default duration
        ]);

        // Create the Questions
        foreach ($request->questions as $q) {
            \App\Models\AssessmentQuestion::create([
                'assessment_id' => $assessment->id,
                'question_text' => $q['question'] ?? $q['question_text'] ?? 'Untitled Question',
                'question_type' => 'mcq',
                'options' => $q['options'],
                'correct_answer' => $q['correct_answer']
            ]);
        }

        return response()->json([
            'status' => 'success',
            'data' => $assessment->load('questions'),
            'message' => 'Assessment saved successfully'
        ]);
    }

    /**
     * Simple test endpoint
     */
    public function test(GeminiService $gemini)
    {
        $result = $gemini->generateContent("Say 'Hello! Gemini is integrated successfully.'");
        
        if ($result['status'] === 'success') {
            return response()->json([
                'status' => 'success',
                'data' => ['response' => $result['content']],
                'message' => 'API is working'
            ]);
        }

        return response()->json($result, 500);
    }
}
